//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonCode
    {
        public CommonCode()
        {
            this.CommitteInfoes = new HashSet<CommitteInfo>();
            this.ContractFields = new HashSet<ContractField>();
            this.Demands = new HashSet<Demand>();
            this.Demands1 = new HashSet<Demand>();
            this.ProjectInstallments = new HashSet<ProjectInstallment>();
            this.TenderSpecifications = new HashSet<TenderSpecification>();
        }

        public long CommonCodeID { get; set; }
        public string BankCode { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public string TypeValue { get; set; }
        public string AdditonalValue { get; set; }
        public string DisplayCode { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }

        public virtual ICollection<CommitteInfo> CommitteInfoes { get; set; }
        public virtual ICollection<ContractField> ContractFields { get; set; }
        public virtual ICollection<Demand> Demands { get; set; }
        public virtual ICollection<Demand> Demands1 { get; set; }
        public virtual ICollection<ProjectInstallment> ProjectInstallments { get; set; }
        public virtual ICollection<TenderSpecification> TenderSpecifications { get; set; }


    }
}
