//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;

    public partial class ContractFile
    {
        public long ContractFileId { get; set; }
        public long DemandId { get; set; }
        public string FileName { get; set; }
        public string FileUrl { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Remarks { get; set; }
        public string Decition { get; set; }
        public string Reference { get; set; }
        public bool IsApproved { get; set; }
        public string ApprovalFileUrl { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApproveRemarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DemandName { set; get; }
        public string Approved { get; set; }
        public virtual Demand Demand { get; set; }
    }
}
