//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlType
    {
        public ControlType()
        {
            this.Demands = new HashSet<Demand>();
        }

        public byte Id { get; set; }
        public string ControlName { get; set; }

        public virtual ICollection<Demand> Demands { get; set; }
    }
}
