//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Department
    {
        public Department()
        {
            this.CommitteInfoes = new HashSet<CommitteInfo>();
            this.DepartmentWiseMileStones = new HashSet<DepartmentWiseMileStone>();
            this.FlowSetups = new HashSet<FlowSetup>();
            this.TenderSpecDeptOpinions = new HashSet<TenderSpecDeptOpinion>();
            this.ContractDeptOpinions = new HashSet<ContractDeptOpinion>();
            this.StaffRequirementDeptOpinions = new HashSet<StaffRequirementDeptOpinion>();
        }
        public long DepartmentId { get; set; }

        [Required(ErrorMessage = "Department name id required")]
        public string Name { get; set; }
        public string UserId { get; set; }
        public string Remarks { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }

        public virtual ICollection<CommitteInfo> CommitteInfoes { get; set; }
        public virtual ICollection<DepartmentWiseMileStone> DepartmentWiseMileStones { get; set; }
        public virtual ICollection<FlowSetup> FlowSetups { get; set; }
        public virtual ICollection<TenderSpecDeptOpinion> TenderSpecDeptOpinions { get; set; }
        public virtual ICollection<ContractDeptOpinion> ContractDeptOpinions { get; set; }
        public virtual ICollection<StaffRequirementDeptOpinion> StaffRequirementDeptOpinions { get; set; }

 
    }
}
