//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentWiseMileStone
    {
        public long Id { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public string MileStoneList { get; set; }
        public string UserId { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<long> EntryDate { get; set; }
        public Nullable<long> LastUpdate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Project Project { get; set; }
    }
}
