//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentInfo
    {
        public long DocumentationInfoIdentity { get; set; }
        public Nullable<long> DocumentType { get; set; }
        public Nullable<long> DocumentId { get; set; }
        public string DocumentRefNo { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string DocumentUrl { get; set; }
        public string UserId { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
