//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileMovement
    {
        public long Id { get; set; }
        public Nullable<long> FileId { get; set; }
        public Nullable<long> DepartmentFrom { get; set; }
        public Nullable<long> DepartmentTo { get; set; }
        public Nullable<System.DateTime> TranferDate { get; set; }
        public Nullable<System.DateTime> DepExpireDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string FileURL { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string UserId { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LastUpadate { get; set; }
    
        public virtual StaffRequirement StaffRequirement { get; set; }
    }
}
