//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public long FileId { get; set; }
        public Nullable<long> StuffRequirementId { get; set; }
        public string FileCode { get; set; }
        public string FileName { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public string FleStetus { get; set; }
        public string FileUrl { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string UserId { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> EntyDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
