//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowSetup
    {
        public long FlowSetupIdentity { get; set; }
        public Nullable<long> FlowId { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public string DepartmentList { get; set; }
        public string FormId { get; set; }
        public string FlowSerial { get; set; }
        public string IsComplete { get; set; }
        public Nullable<bool> IsSkip { get; set; }
        public string SkipStatus { get; set; }
        public string TaskSerial { get; set; }
        public string SkipRemarks { get; set; }
        public Nullable<System.DateTime> DepStartDate { get; set; }
        public Nullable<System.DateTime> DepEndDate { get; set; }
        public Nullable<System.DateTime> ActDepEndDate { get; set; }
        public string UserId { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string FlowName { get; set; }
        public virtual Demand Demand { get; set; }
        public virtual Department Department { get; set; }
    }
}
