//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.CommitteInfoes = new HashSet<CommitteInfo>();
        }

        public long MemberId { get; set; }
        public Nullable<long> Rank { get; set; } 
        public string OfficeId { get; set; }
        public string MemberName { get; set; }
        public string ImageUrl { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string UserId { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }

        public virtual ICollection<CommitteInfo> CommitteInfoes { get; set; }
    }
}
