//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectFinalStatu
    {
        public long ProjectIdentity { get; set; }
        public string ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> Status { get; set; }
        public string PStatusName { get; set; }
        public Nullable<int> MileStone { get; set; }
        public Nullable<int> FinalStatus { get; set; }
    }
}
