//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectFileMovement
    {
        public Nullable<long> SerialNo { get; set; }
        public long ProjectIdentity { get; set; }
        public Nullable<long> StuffRequirementId { get; set; }
        public string ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<decimal> ProjectValue { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<int> Status { get; set; }
        public string PStatusName { get; set; }
        public Nullable<int> ProjectFlow { get; set; }
        public string DepartmentList { get; set; }
        public Nullable<int> FlowId { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public Nullable<int> Milestone { get; set; }
        public string DepartmentFrom { get; set; }
        public string DepartmentTo { get; set; }
        public string FMStatusId { get; set; }
        public string FMStatus { get; set; }
    }
}
