//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public long ProjectIdentity { get; set; }
        public Nullable<long> StuffRequirementId { get; set; }
        public string ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<decimal> ProjectValue { get; set; }
        public Nullable<byte> ProjectType { get; set; }
        public string ProjectRequirement { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ProjectFlow { get; set; }
        public string FileURL { get; set; }
        public string DepartmentList { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string UserId { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
