//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStatu
    {

        public long ProjectId { get; set; }
        public int CompleteMileStone { get; set; }
        public string ProjectName { get; set; }
        public string ProjectType { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public string DeptName { get; set; }
        public string PendingDays { get; set; }
        public int? Complete { get; set; }
    }
}
