//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffRequirement
    {
        public StaffRequirement()
        {
            this.FileMovements = new HashSet<FileMovement>();
        }

        public long StuffRequirementId { get; set; }
        public Nullable<long> FileNo { get; set; }
        public string Title { get; set; }
        public string FileUrl { get; set; }
        public Nullable<long> CommitteID { get; set; }
        public Nullable<long> FlowId { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Remarks { get; set; }
        public string Decition { get; set; }
        public string Reference { get; set; }
        public bool IsApprove { get; set; }
        public string ApproveFile { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApproveRemarks { get; set; }
        public string UserId { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }


        public virtual ICollection<FileMovement> FileMovements { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
