//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.StaffRequirements = new HashSet<StaffRequirement>();
        }

        public byte Id { get; set; }
        public string FileStatus { get; set; }

        public virtual ICollection<StaffRequirement> StaffRequirements { get; set; }
    }
}
