//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBankInfo
    {
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string RoleName { get; set; }
        public string PhoneNumber { get; set; }
        public string UserEmail { get; set; }
        public long BranchInfoIdentity { get; set; }
        public string Code { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string DistrictCode { get; set; }
        public string DistrictName { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public Nullable<long> CountryCode { get; set; }
        public string BranchType { get; set; }
        public string NativeBranchCode { get; set; }
        public string SubBranchCode { get; set; }
        public string SubBranchName { get; set; }
        public string BranchLevel { get; set; }
        public string RoutingNo { get; set; }
        public string Address { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string ServerName { get; set; }
        public string IsAdviceRespond { get; set; }
        public string SubBranchAddress { get; set; }
        public Nullable<decimal> MinimumCoverFund { get; set; }
        public Nullable<decimal> MinimumNRDBalance { get; set; }
        public Nullable<byte> WorkingTimeFrom { get; set; }
        public Nullable<byte> WorkingTimeTo { get; set; }
        public bool ApprovedUser { get; set; }
        public bool WinPassword { get; set; }
        public bool IsFirstTime { get; set; }
        public string AspUserFullName { get; set; }
        public int AspRoleId { get; set; }
        public string AspRoleShortName { get; set; }
        public string IPAddress { get; set; }
        public string HostName { get; set; }
        public long IsLogin { get; set; }
    }
}
