//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long UserId { get; set; }
        public int RoleId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string LoweredUserName { get; set; }
        public string MobileAlias { get; set; }
        public bool IsAnonymous { get; set; }
        public System.DateTime LastActivityDate { get; set; }
        public long BranchInfoIdentity { get; set; }
        public bool WinPassword { get; set; }
        public string UserFullName { get; set; }
        public Nullable<decimal> TransLimit { get; set; }
        public string Createdby { get; set; }
        public bool ApprovedUser { get; set; }
        public Nullable<decimal> VerifyLimit { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string SecurityQustion { get; set; }
        public string Answer { get; set; }
        public string BankCode { get; set; }
        public Nullable<int> AttemptCount { get; set; }
        public string ParmitedBy { get; set; }
        public Nullable<System.DateTime> UserExpiryDate { get; set; }
        public Nullable<int> PasswordValidity { get; set; }
        public Nullable<System.DateTime> PasswordChangeDate { get; set; }
        public Nullable<System.DateTime> LasUpdateDate { get; set; }
        public bool IsFirstTime { get; set; }
        public long IsLogin { get; set; }
        public string IPAddress { get; set; }
        public string HostName { get; set; }
    
        public virtual BranchInfo BranchInfo { get; set; }
        public virtual Role Role { get; set; }
    }
}
